<#
.SYNOPSIS
    Live demo script for Fabric CI/CD Option 2.
    Run this AFTER setup-demo.ps1 has completed and validation pipeline succeeded.

.DESCRIPTION
    Walks through the live demo flow:
    1. Explain the architecture (multi-stage pipeline, not branch-triggered)
    2. Create a feature branch and make a visible change
    3. Push and create a PR to main
    4. (Manual) Merge PR -> pipeline triggers -> deploys to Dev -> approval gate -> deploys to Test
    5. Verify results in Fabric portal

.PARAMETER ConfigFile
    Path to demo-config.json generated by setup-demo.ps1.
    When provided, all other parameters are loaded from the file and can be omitted.
.PARAMETER RepoPath
    Local path to the cloned demo repo (output from setup-demo.ps1).
.PARAMETER AzDoOrg
    Full URL of your Azure DevOps organization.
.PARAMETER AzDoProject
    Azure DevOps project name.
.PARAMETER AzDoRepo
    Azure DevOps repository name.
#>

param(
    [Parameter(Mandatory = $false)]
    [string]$ConfigFile,

    [Parameter(Mandatory = $false)]
    [string]$RepoPath,

    [Parameter(Mandatory = $false)]
    [string]$AzDoOrg,

    [Parameter(Mandatory = $false)]
    [string]$AzDoProject,

    [Parameter(Mandatory = $false)]
    [string]$AzDoRepo = "fabric-demo-repo"
)

# ============================================================================
# Load config file if provided — individual params override config values
# ============================================================================
if ($ConfigFile) {
    if (-not (Test-Path $ConfigFile)) {
        Write-Host "ERROR: Config file not found: $ConfigFile" -ForegroundColor Red
        exit 1
    }
    $cfg = Get-Content $ConfigFile -Raw | ConvertFrom-Json
    if (-not $RepoPath)    { $RepoPath    = $cfg.RepoPath }
    if (-not $AzDoOrg)     { $AzDoOrg     = $cfg.AzDoOrg }
    if (-not $AzDoProject) { $AzDoProject = $cfg.AzDoProject }
    if (-not $AzDoRepo -or $AzDoRepo -eq "fabric-demo-repo") { $AzDoRepo = $cfg.AzDoRepo }
}

# Validate required values
if (-not $RepoPath)    { Write-Host "ERROR: -RepoPath is required (or provide -ConfigFile)" -ForegroundColor Red; exit 1 }
if (-not $AzDoOrg)     { Write-Host "ERROR: -AzDoOrg is required (or provide -ConfigFile)" -ForegroundColor Red; exit 1 }
if (-not $AzDoProject) { Write-Host "ERROR: -AzDoProject is required (or provide -ConfigFile)" -ForegroundColor Red; exit 1 }

function Write-Step {
    param([int]$Number, [string]$Description)
    Write-Host ""
    Write-Host "------------------------------------------------------------" -ForegroundColor Cyan
    Write-Host " Demo Step ${Number}: ${Description}" -ForegroundColor Cyan
    Write-Host "------------------------------------------------------------" -ForegroundColor Cyan
}

function Pause-Demo {
    param([string]$Message)
    Write-Host ""
    Write-Host "[DEMO PAUSE] $Message" -ForegroundColor Yellow
    Read-Host "Press ENTER to continue..."
}

# ============================================================================
# Configure defaults
# ============================================================================
az devops configure --defaults organization=$AzDoOrg project=$AzDoProject

# ============================================================================
# Step 1: Show the architecture
# ============================================================================
Write-Step 1 "Explain the Architecture"
Write-Host @"

  Architecture Overview (Git-Based Deployments Using Build Environments):

  Feature Branch      PR        main branch              Pipeline (multi-stage)
  +-----------+    +------+    +------------+    +-------------------------------------+
  | Edit item | -> | PR   | -> | Merge     | -> | Stage 1: Deploy to Dev (Demo-Dev)   |
  | definition|    | review|    |           |    |   - fabric-cicd publish_all_items    |
  +-----------+    +------+    +------------+    |   - post-deployment rebinding        |
                                                 +------------------+------------------+
                                                                    |
                                                                    v (approval gate)
                                                 +------------------+------------------+
                                                 | Stage 2: Deploy to Test (Demo-Test) |
                                                 |   - fabric-cicd publish_all_items    |
                                                 |   - post-deployment rebinding        |
                                                 +-------------------------------------+

  Key points:
  - Single pipeline triggered on merge to main, with sequential stages
  - Workspaces are NOT Git-connected; all deploys come from the pipeline
  - Workspace names stored in variable group: mainWorkspaceName, testWorkspaceName
  - Service Principal auth; secrets in Key Vault
  - fabric-cicd library handles Fabric item create/update/delete via REST API
  - Post-deployment step rebinds connections, notebooks, semantic models, reports
  - 6 item types: Notebook, DataPipeline, Lakehouse, SemanticModel, Report, Warehouse

  Feature branch workflow:
  - Notebooks (.py): edit directly in Git
  - Visual items (Pipelines, Reports, Semantic Models): author in Fabric portal,
    temporarily connect workspace to feature branch to export, then disconnect

"@ -ForegroundColor White

Pause-Demo "Show the readme diagram and explain, then continue"

# ============================================================================
# Step 2: Create a feature branch and make a change
# ============================================================================
Write-Step 2 "Create Feature Branch & Make a Change"

Push-Location $RepoPath

# Clean up any leftover state from previous demo runs
Write-Host "Resetting repo to clean state..." -ForegroundColor Gray
git checkout main 2>$null
if ($LASTEXITCODE -ne 0) {
    # main might not exist locally yet, or working tree is dirty
    git stash --include-untracked 2>$null
    git checkout main 2>$null
    if ($LASTEXITCODE -ne 0) {
        # Still failing — force reset
        git checkout -f main 2>$null
    }
}
git reset --hard origin/main 2>$null
git clean -fd 2>$null
git pull origin main
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Could not pull main branch. Check repo path and remote connectivity." -ForegroundColor Red
    Pop-Location
    exit 1
}

# Delete any leftover feature branches from previous runs
git branch --list 'feature/*' | ForEach-Object { git branch -D $_.Trim() 2>$null }

$branchName = "feature/update-notebook-$(Get-Date -Format 'MMdd-HHmm')"
git checkout -b $branchName

Write-Host ""
Write-Host "Feature branch created: $branchName" -ForegroundColor Green
Write-Host ""

# Find a notebook definition to modify
$notebookDir = Get-ChildItem -Path "fabric" -Directory -Recurse | Where-Object { $_.Name -like "*.Notebook" } | Select-Object -First 1

if ($notebookDir) {
    Write-Host "Found notebook: $($notebookDir.FullName)" -ForegroundColor Green

    $pyFile = Get-ChildItem -Path $notebookDir.FullName -Filter "*.py" | Select-Object -First 1
    $jsonFile = Get-ChildItem -Path $notebookDir.FullName -Filter "*.json" -Recurse | Select-Object -First 1

    if ($pyFile) {
        $content = Get-Content $pyFile.FullName -Raw
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $newContent = $content + "`n# Demo change added on $timestamp`nprint('CI/CD demo - deployed automatically!')`n"
        $newContent | Set-Content $pyFile.FullName -Encoding utf8
        Write-Host "  Modified: $($pyFile.FullName)" -ForegroundColor Green
    } elseif ($jsonFile) {
        Write-Host "  Found JSON definition: $($jsonFile.FullName)" -ForegroundColor Green
        Write-Host "  Edit this file manually to add a visible change" -ForegroundColor Yellow
    }
} else {
    Write-Host "No notebook found in fabric/ folder." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  For visual items (Pipelines, Reports, Semantic Models):" -ForegroundColor White
    Write-Host "  1. Open Fabric portal -> Demo-Dev workspace" -ForegroundColor White
    Write-Host "  2. Make your change (e.g., edit a pipeline or report)" -ForegroundColor White
    Write-Host "  3. Settings -> Git integration -> connect to branch '$branchName' + folder 'fabric/'" -ForegroundColor White
    Write-Host "  4. Commit & sync to export the definition" -ForegroundColor White
    Write-Host "  5. Disconnect the workspace from Git" -ForegroundColor White
}

Pause-Demo "Review the change, then continue to commit and push"

# ============================================================================
# Step 3: Commit, push, and create PR
# ============================================================================
Write-Step 3 "Commit, Push, and Create PR to main"

git add .
git commit -m "Demo: Update notebook with CI/CD demo cell"
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Git commit failed. Nothing to commit?" -ForegroundColor Red
    Pop-Location
    exit 1
}

git push origin $branchName
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Git push failed. Check credentials and remote access." -ForegroundColor Red
    Pop-Location
    exit 1
}

Write-Host ""
Write-Host "Creating Pull Request..." -ForegroundColor Green

$prJson = az repos pr create `
    --repository $AzDoRepo `
    --source-branch $branchName `
    --target-branch main `
    --title "Demo: Update notebook with new cell" `
    --description "This PR demonstrates the CI/CD flow. Merging will trigger the deployment pipeline." `
    --output json 2>&1

try {
    $pr = $prJson | ConvertFrom-Json
    Write-Host "PR #$($pr.pullRequestId) created" -ForegroundColor Green
    $prUrl = "$AzDoOrg/$AzDoProject/_git/$AzDoRepo/pullrequest/$($pr.pullRequestId)"
    Write-Host "  URL: $prUrl" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] Failed to create PR. Output:" -ForegroundColor Red
    Write-Host $prJson -ForegroundColor Red
    $prUrl = "$AzDoOrg/$AzDoProject/_git/$AzDoRepo/pullrequests"
    Write-Host "  Check manually: $prUrl" -ForegroundColor Yellow
}

Pop-Location

# ============================================================================
# Step 4: Merge and show pipeline (both stages)
# ============================================================================
Write-Step 4 "Merge PR & Watch Pipeline Deploy to Dev and Test"

Write-Host @"

  MANUAL STEPS:
  1. Go to Azure DevOps: $prUrl
  2. Review the PR -- show the diff
  3. Approve and Complete the merge

  PIPELINE RUNS (single pipeline, two stages):

  Stage 1 -- Deploy to Dev:
  4. Navigate to Pipelines -- show the triggered run
     -> Highlight: pip install fabric-cicd, SP auth, workspace lookup, publish_all_items
  5. After deploy completes, post-deployment runs automatically:
     -> Rebinds notebooks (lakehouse/warehouse references)
     -> Rebinds data pipelines (connection IDs, linked services, activity refs)
     -> Rebinds semantic models (Direct Lake or M expression connections)
     -> Rebinds reports (semantic model references)
  6. Open Fabric portal: https://app.fabric.microsoft.com
     -> Navigate to 'Demo-Dev' workspace
     -> Open the HelloWorld notebook and show the new cell/change

  Stage 2 -- Deploy to Test (with approval gate):
  7. The APPROVAL GATE fires -- approve it in the pipeline run
  8. Same process: fabric-cicd deploys items, then post-deployment rebinds
  9. Open Fabric portal -> 'Demo-Test' workspace
     -> Verify the same changes are deployed to Test

"@ -ForegroundColor Yellow

Pause-Demo "Complete the above steps"

# ============================================================================
# Done
# ============================================================================
Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host " DEMO COMPLETE!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Recap:" -ForegroundColor White
Write-Host "  1. Feature branch created with a Notebook change"
Write-Host "  2. PR merged to main -> pipeline triggered"
Write-Host "  3. Stage 1: fabric-cicd deployed to Demo-Dev + post-deployment rebinding"
Write-Host "  4. Stage 2: approval gate -> deployed to Demo-Test + post-deployment rebinding"
Write-Host "  5. All 6 item types (incl. Warehouse) handled by fabric-cicd"
Write-Host ""
Write-Host "Key takeaways:" -ForegroundColor White
Write-Host "  - Git is the single source of truth"
Write-Host "  - Workspaces are NOT Git-connected; pipeline deploys from Git"
Write-Host "  - Single multi-stage pipeline with approval gates between stages"
Write-Host "  - Post-deployment auto-rebinds connections, notebooks, models, reports"
Write-Host "  - Service Principal auth with Key Vault secrets"
Write-Host "  - Visual items: author in Fabric, temp Git connect to export, then disconnect"
Write-Host ""
